version: '3.6'

networks:
    default:
        driver: bridge

services:
  micrometer-spring-boot-sandbox:
    container_name: micrometer-sandbox-application
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
        
  prometheus:
    container_name: micrometer-sandbox-prometheus
    image: prom/prometheus
    depends_on:
      - micrometer-spring-boot-sandbox
    volumes:
      - ./docker/env/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  grafana:
    container_name: micrometer-sandbox-grafana
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    env_file:
      - docker/env/grafana.env